[package]
name = "bears-reloaded-management"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "0.9.3"
clap = { version = "4.0.9", features = ["derive"] }
mpl-token-metadata = "~1.3.6"
# serde_json = "1.0.86"
solana-client = "1.14.5"
solana-sdk = "1.14.5"